### PR TITLE
Upgrade to Debian Buster

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by tianon** [comment]
Given that these are too heavy for Travis to test, have you build-tested these locally?

**Comment by tianon** [comment]
(I've got some local build tests going but yours might finish faster than I get back to this machine to paste them.)

**Comment by J0WI** [comment]
I don't have the capacity to build all variants locally, but I can try to build one on `amd64`.

**Comment by J0WI** [comment]
GCC 9.1 was successful on Buster

**Comment by tianon** [comment]
Nice, thanks!  I managed to get a quick test done on the others as well:

```console
$ for v in 7 8 9; do wget -qO- 'https://github.com/docker-library/gcc/raw/035d5baa91016103e8f5231b6d589054381b0f55/'"$v"'/Dockerfile' | docker build -q -; done
sha256:df7124cb427c0b3c28cb18b5428eb8edad2545532721d26168f05cf51160feac
sha256:249044c91296bc12278b97ebc9e5c70000fa9052e8ca4b6703eb8dd68968a0bc
sha256:3a16a9b88d33692f57357c05da340daab93cdb010ef97583aad1b5493c061d70
```

**Pull request merged**
