### PR TITLE
Build gccgo 5.3 for ppc64le

### PR DESCRIPTION
**Pull request by clnperez**
Signed-off-by: Christy Perez <christy@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by yosifkit** [comment]
We unfortunately have no way of supporting different architectures in the official images.

**Comment by clnperez** [comment]
@tianon actually has already facilitated an environment for this, so I was trying to make life a little easier for him by officially adding the ppc64le dockerfile (which I've tested with) to this repo.

**Comment by tianon** [comment]
I appreciate the thought, but I don't think we're ready to fully commit to mutli-arch support just yet.  However, that being said, I do have this repo auto-building on ppc64le via https://github.com/tianon/jenkins-groovy/blob/master/dsl/docker-multiarch/images/gcc.groovy (as described in https://github.com/docker-library/official-images/blob/master/README.md#architectures-other-than-amd64 via https://github.com/docker-library/official-images/pull/1310).

**Comment by clnperez** [comment]
Ok, I think I just had a different interpretation of multi-arch "support." I looked through all the doc for how this process works and I think I get where you're coming from now.

Great news about the auto-building. Let me know if you ever need anything!

**Pull request closed without merging**
