### PR TITLE
add gcc 12.1.0

### PR DESCRIPTION
**Pull request by kasperk81**
news: https://gcc.gnu.org/gcc-12/

### CODE REVIEW

**Comment by kasperk81** [comment]
@tianon, 12.1 was released today. i have used scripts to update it, might have missed something. could you take a look?

**Comment by kasperk81** [comment]
building in fork's actions https://github.com/kasperk81/gcc/actions/runs/2282586019

**Comment by kasperk81** [comment]
@yosifkit thanks for running the ci checks.

**Comment by yosifkit** [comment]
Thanks for the PR!

**Comment by kasperk81** [comment]
@yosifkit do i need to open a pr like https://github.com/docker-library/official-images/pull/12284 in official-images to get 12.1 published to docker hub?

**Comment by yosifkit** [comment]
That is what controls the updates pushed to Docker hub. We do them periodically when there is a change. I'd like to get #84 in the update too, so I'll open one after we merge that.

**Comment by kasperk81** [comment]
great, thanks. :+1:

**Pull request merged**
