### PR TITLE
Remove 4.6

### PR DESCRIPTION
**Pull request by tianon**
These older releases are unsupported upstream.  If you visit https://gcc.gnu.org/, you can see that currently, only 4.8.4 and 4.9.2 are supported, and they're both in "regression fixes and docs only" mode (as is the in-development 5.0 branch).

### CODE REVIEW

**Comment by tianon** [comment]
This might actually be incorrect, but I can't find anything definitively saying either way.

https://gcc.gnu.org/releases.html mentions:
> Note that starting with version 3.3.4, we provide bug releases for older release branches for those users who require a very high degree of stability.

Maintaining images for all versions down to 3.3 seems incredibly insane since they're not at all likely to receive any updates (to contrast, 4.7 is number 4 on the scale of "most recently updated", right after 4.8 and 2x4.9).

**Comment by tianon** [comment]
Last updated:
- 4.9: October 30, 2014
- 4.8: December 19, 2014
- 4.7: June 12, 2014
- 4.6: April 12, 2013
- 4.5: July 2, 2012
- 4.4: March 13, 2012
- 4.3: June 27, 2011

**Comment by tianon** [comment]
So, I'm leaning towards dropping this PR down to just removing 4.6 since it didn't see a single minor release all last year.

**Comment by mpapierski** [comment]
I'm not sure about dropping 4.6 and 4.7 completely from the library. For example Ubuntu 12.04 LTS still distributes 4.6.3 and it looks for me like its just old, and not broken. Ubuntu package changelog doesnt give me any clue about patches they incorporate into their package.

Can you clarify your points why it might be good idea to drop 4.6 (and possibly 4.7)?

**Comment by tianon** [comment]
The rationale was that they're old and supposedly unsupported upstream and
thus only introducing a maintenance and compute burden, but that's clearly
not the case.  It might actually make sense to broaden the number of
versions we support, but my cycles cry at the thought. :cry:

**Comment by yosifkit** [comment]
We could add the extra versions, then drop them (they'll still be available on the hub, just not updated with base image changes) until they get a version bump (which is minimum 2 months between patches in gcc land).

https://gcc.gnu.org/develop.html#timeline shows that they have only updated for 2-3 years beyond release.

**Pull request closed without merging**
