### PR TITLE
Add alpine based image

### PR DESCRIPTION
**Pull request by cpuguy83**
This one comes in at ~82MB, compared to 1GB for the other images.

### CODE REVIEW

**Comment by tianon** [comment]
This is a good start, but this is going to need to be a variant of an existing version, with the goal of keeping the delta between the standard variant and the Alpine variant as minimal as possible, especially to keep consistency in the way it's used.

Usually we've been targeting parity with `slim` variants, since most repos have those already, but the `gcc` repo is so dead and unused (since nobody really compiles and uses `gcc` this way commonly) so it doesn't have `slim` variants yet, and it takes long enough to compile that I'm honestly closer to a -1 on adding more variants unless there's some strong justification for them.

**Comment by cpuguy83** [comment]
fair enough, thanks.

**Comment by Starbix** [comment]
Hey is this repo still dead?

I've started working on an Alpine based image with a recent gcc version: https://github.com/Starbix/dockerimages/blob/master/base/Dockerfile

The image is only 16 MB (there's no make etc. though).

**Comment by tianon** [comment]
It's not really "dead" per-se -- we still update `gcc` to newer versions, but it is so heavy (and takes so long) to compile `gcc` that we've kept the variants intentionally light.  I don't think our infrastructure could handle an explosion of `gcc` variants very well. :sweat_smile:

**Comment by Starbix** [comment]
Yeah that makes sense if there still isn't a huge demand for it. 😄
Then I'll just use my own version, still thank you for your answer!

**Pull request closed without merging**
