### PR TITLE
use "https" to fetch GCC Packages

### PR DESCRIPTION
**Pull request by J0WI**

### CODE REVIEW

**Comment by J0WI** [comment]
Maybe this can also be used as `packagesUrl`, because the markup of the GNU FTP server will not change often.

**Comment by tianon** [comment]
Doesn't GNU request that downstreams use `ftpmirror` instead so that we aren't putting quite so much load on their main FTP server?

**Comment by tianon** [comment]
(and we do check the GPG signature of the file we download, which should give us stronger assurances than TLS does)

**Comment by J0WI** [comment]
https://www.gnu.org/prep/ftp.html says:
> Please try to use one of the many mirrors of our site listed below: the mirrors will give you faster response.

So its just about the latency or the bandwidth on the users side. The file is only downloaded once on build time, so I think it does not produce that much load.

Of course TLS does not replace a GPG signature, but https has some benefits compared to plain http.

**Comment by tianon** [comment]
Right, it is only at build time, but we have CI, etc that does builds quite
often.

**Comment by J0WI** [comment]
`ftpmirror.gnu.org` does also support https, but it may redirect to a http mirror. We could also hardcode a https mirror.

**Comment by J0WI** [comment]
@tianon I tested it from a few different locations and it seems that `httpS://ftpmirror.gnu.org/` does always prefer a httpS mirror. Sadly Travis is not yet activated in this repo.

In a further step, the `packagesUrl` in `update.sh` may be changed to `https://ftp.gnu.org/gnu/gcc/` to be a bit more upstream for version grepping, which does not use much bandwidth.

**Comment by tianon** [comment]
Sure, seems fair!  Thanks.

As a side note, we don't enable Travis here because it takes `gcc` so long to compile that it usually fails, and we're thus simply wasting Travis resources.

**Pull request merged**
